name: adroid
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.0.17

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  bloc_test: ^9.1.1

dependency_overrides:
  test_api: 0.4.16

flutter:
  uses-material-design: true
