// Mocks generated by Mockito 5.3.2 from annotations
// in adroid/test/features/historical/data/repositories/historical_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:adroid/core/network/network_info.dart' as _i6;
import 'package:adroid/features/historical/data/datasources/historical_local_data_source.dart'
    as _i4;
import 'package:adroid/features/historical/data/datasources/historical_remote_data_source.dart'
    as _i3;
import 'package:adroid/features/historical/data/models/historical_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHistoricalModel_0 extends _i1.SmartFake
    implements _i2.HistoricalModel {
  _FakeHistoricalModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HistoricalRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoricalRemoteDataSource extends _i1.Mock
    implements _i3.HistoricalRemoteDataSource {
  MockHistoricalRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [HistoricalLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoricalLocalDataSource extends _i1.Mock
    implements _i4.HistoricalLocalDataSource {
  MockHistoricalLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.HistoricalModel> getSavedHistory() => (super.noSuchMethod(
        Invocation.method(
          #getSavedHistory,
          [],
        ),
        returnValue:
            _i5.Future<_i2.HistoricalModel>.value(_FakeHistoricalModel_0(
          this,
          Invocation.method(
            #getSavedHistory,
            [],
          ),
        )),
      ) as _i5.Future<_i2.HistoricalModel>);
  @override
  _i5.Future<void> cahceHistory(_i2.HistoricalModel? historicaltoChache) =>
      (super.noSuchMethod(
        Invocation.method(
          #cahceHistory,
          [historicaltoChache],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
